owner: sourceplusplus # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Source++ Website
    url: https://sourceplus.plus
  - name: Source++ Documentation
    url: https://docs.sourceplus.plus
  - name: Source++ Cloud
    url: https://cloud.sourceplus.plus

status-website:
  cname: status.sourceplus.plus
  themeUrl: https://cdn.statically.io/gh/sourceplusplus/status/master/assets/spp-theme-v3.css #todo: shouldn't need statically
  logoUrl: https://sourceplus.plus/assets/logo/logo-dark.svg
  name: Status | Source++
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees: # Users to assign downtime issues (optional)
  - bfergerson

graphBackgroundColor: "#e6e6e6"
graphBorderColor: "#20bf6b"

i18n:
  footer: ""

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
